server {
    listen 80;
    server_name saramedico.com www.saramedico.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name saramedico.com www.saramedico.com;

    ssl_certificate /etc/letsencrypt/live/saramedico.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/saramedico.com/privkey.pem;

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}