"""Add contact_messages table

Revision ID: contact_001
Revises: a1b2c3d4e5f7
Create Date: 2026-03-16 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'contact_001'
down_revision = 'a1b2c3d4e5f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.String(255), nullable=False),
    sa.Column('last_name', sa.String(255), nullable=False),
    sa.Column('email', sa.String(255), nullable=False),
    sa.Column('phone', sa.String(20), nullable=False),
    sa.Column('subject', sa.String(255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contact_messages_created_at', 'contact_messages', ['created_at'], unique=False)
    op.create_index('ix_contact_messages_email', 'contact_messages', ['email'], unique=False)
    op.create_index('ix_contact_messages_first_name', 'contact_messages', ['first_name'], unique=False)
    op.create_index('ix_contact_messages_read', 'contact_messages', ['read'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contact_messages_read', table_name='contact_messages')
    op.drop_index('ix_contact_messages_first_name', table_name='contact_messages')
    op.drop_index('ix_contact_messages_email', table_name='contact_messages')
    op.drop_index('ix_contact_messages_created_at', table_name='contact_messages')
    op.drop_table('contact_messages')
    # ### end Alembic commands ###
