"""fix_chunk_patient_id_fk_to_patients

Revision ID: aee7cd30e55f
Revises: a211f97aebb3
Create Date: 2026-03-02 22:28:22.702451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aee7cd30e55f'
down_revision: Union[str, None] = 'a211f97aebb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_metrics_patient_id', table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index('ix_recent_patients_doctor_id', table_name='recent_patients')
    op.drop_index('ix_recent_patients_patient_id', table_name='recent_patients')
    op.drop_table('recent_patients')
    op.drop_index('ix_recent_doctors_doctor_id', table_name='recent_doctors')
    op.drop_index('ix_recent_doctors_patient_id', table_name='recent_doctors')
    op.drop_table('recent_doctors')
    op.drop_constraint('chunks_patient_id_fkey', 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'patients', ['patient_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key('chunks_patient_id_fkey', 'chunks', 'users', ['patient_id'], ['id'])
    op.create_table('recent_doctors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_doctors_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_doctors_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_doctors_pkey')
    )
    op.create_index('ix_recent_doctors_patient_id', 'recent_doctors', ['patient_id'], unique=False)
    op.create_index('ix_recent_doctors_doctor_id', 'recent_doctors', ['doctor_id'], unique=False)
    op.create_table('recent_patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_patients_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_patients_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_patients_pkey')
    )
    op.create_index('ix_recent_patients_patient_id', 'recent_patients', ['patient_id'], unique=False)
    op.create_index('ix_recent_patients_doctor_id', 'recent_patients', ['doctor_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='health_metrics_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='health_metrics_pkey')
    )
    op.create_index('ix_health_metrics_patient_id', 'health_metrics', ['patient_id'], unique=False)
    # ### end Alembic commands ###
