"""restore_missing_tables_from_init

Revision ID: 740e05463f91
Revises: 55aa6ec02023
Create Date: 2026-03-01 16:01:13.997238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '740e05463f91'
down_revision: Union[str, None] = '55aa6ec02023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Restore missing tables conditionally
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    tables = inspector.get_table_names()
    
    if 'health_metrics' not in tables:
        op.create_table('health_metrics',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
        sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='health_metrics_patient_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='health_metrics_pkey')
        )
        op.create_index('ix_health_metrics_patient_id', 'health_metrics', ['patient_id'], unique=False)
    
    if 'recent_patients' not in tables:
        op.create_table('recent_patients',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_patients_doctor_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_patients_patient_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='recent_patients_pkey')
        )
        op.create_index('ix_recent_patients_patient_id', 'recent_patients', ['patient_id'], unique=False)
        op.create_index('ix_recent_patients_doctor_id', 'recent_patients', ['doctor_id'], unique=False)
    
    if 'recent_doctors' not in tables:
        op.create_table('recent_doctors',
        sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
        sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_doctors_doctor_id_fkey', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_doctors_patient_id_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='recent_doctors_pkey')
        )
        op.create_index('ix_recent_doctors_patient_id', 'recent_doctors', ['patient_id'], unique=False)
        op.create_index('ix_recent_doctors_doctor_id', 'recent_doctors', ['doctor_id'], unique=False)

    op.alter_column('data_access_grants', 'ai_access_permission',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('data_access_grants', 'access_level',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'total_chunks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('data_access_grants', 'access_level',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'standard'::character varying"),
               existing_nullable=False)
    op.alter_column('data_access_grants', 'ai_access_permission',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
