"""add_timezone_to_org

Revision ID: 0422ec1b753a
Revises: f8a2b4c6d7e8
Create Date: 2026-03-07 18:47:32.760852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0422ec1b753a'
down_revision: Union[str, None] = 'f8a2b4c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), server_default='UTC', nullable=True))
    op.add_column('organizations', sa.Column('date_format', sa.String(length=100), server_default='DD/MM/YYYY', nullable=True))
    op.add_column('organizations', sa.Column('org_email', sa.String(length=255), nullable=True))
    
    op.drop_column('users', 'onboarding_complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'org_email')
    op.drop_column('organizations', 'date_format')
    op.drop_column('organizations', 'timezone')
    op.add_column('users', sa.Column('onboarding_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
