"""add ai_access_permission to data_access_grants

Revision ID: a211f97aebb3
Revises: f4ff70557c75
Create Date: 2026-03-02 18:56:46.253010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a211f97aebb3'
down_revision: Union[str, None] = 'f4ff70557c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_metrics_patient_id', table_name='health_metrics')
    op.drop_table('health_metrics')
    op.drop_index('ix_recent_doctors_doctor_id', table_name='recent_doctors')
    op.drop_index('ix_recent_doctors_patient_id', table_name='recent_doctors')
    op.drop_table('recent_doctors')
    op.drop_index('ix_recent_patients_doctor_id', table_name='recent_patients')
    op.drop_index('ix_recent_patients_patient_id', table_name='recent_patients')
    op.drop_table('recent_patients')
    op.add_column('data_access_grants', sa.Column('ai_access_permission', sa.Boolean(), nullable=False))
    op.add_column('data_access_grants', sa.Column('access_level', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('processing_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'processing_details')
    op.drop_column('data_access_grants', 'access_level')
    op.drop_column('data_access_grants', 'ai_access_permission')
    op.create_table('recent_patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_patients_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_patients_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_patients_pkey')
    )
    op.create_index('ix_recent_patients_patient_id', 'recent_patients', ['patient_id'], unique=False)
    op.create_index('ix_recent_patients_doctor_id', 'recent_patients', ['doctor_id'], unique=False)
    op.create_table('recent_doctors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_doctors_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_doctors_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_doctors_pkey')
    )
    op.create_index('ix_recent_doctors_patient_id', 'recent_doctors', ['patient_id'], unique=False)
    op.create_index('ix_recent_doctors_doctor_id', 'recent_doctors', ['doctor_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='health_metrics_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='health_metrics_pkey')
    )
    op.create_index('ix_health_metrics_patient_id', 'health_metrics', ['patient_id'], unique=False)
    # ### end Alembic commands ###
