"""update_user_model_auth_and_status

Revision ID: cc6e35d530a0
Revises: contact_001
Create Date: 2026-03-23 17:50:43.942482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc6e35d530a0'
down_revision: Union[str, None] = 'contact_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    auth_provider_enum = postgresql.ENUM('email', 'google', 'apple', name='auth_provider_enum')
    auth_provider_enum.create(op.get_bind())
    
    account_status_enum = postgresql.ENUM('pending_onboarding', 'pending_verification', 'active', 'suspended', name='account_status')
    account_status_enum.create(op.get_bind())
    
    op.add_column('users', sa.Column('auth_provider', sa.Enum('email', 'google', 'apple', name='auth_provider_enum'), server_default='email', nullable=False))
    op.add_column('users', sa.Column('account_status', sa.Enum('pending_onboarding', 'pending_verification', 'active', 'suspended', name='account_status'), server_default='active', nullable=False))
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_column('users', 'account_status')
    op.drop_column('users', 'auth_provider')
    # ### end Alembic commands ###
