"""add_timezone_to_org

Revision ID: 0422ec1b753a
Revises: f8a2b4c6d7e8
Create Date: 2026-03-07 18:47:32.760852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0422ec1b753a'
down_revision: Union[str, None] = 'f8a2b4c6d7e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_doctor_statuses_id', table_name='doctor_statuses')
    op.drop_table('doctor_statuses')
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_chat_sessions_doctor_patient', table_name='chat_sessions')
    op.create_index('ix_chunk_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('notifications', 'action_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('organizations', sa.Column('timezone', sa.String(length=100), server_default='UTC', nullable=True))
    op.add_column('organizations', sa.Column('date_format', sa.String(length=100), server_default='DD/MM/YYYY', nullable=True))
    op.add_column('organizations', sa.Column('org_email', sa.String(length=255), nullable=True))
    
    op.drop_column('users', 'onboarding_complete')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'org_email')
    op.drop_column('organizations', 'date_format')
    op.drop_column('organizations', 'timezone')
    op.add_column('users', sa.Column('onboarding_complete', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.alter_column('notifications', 'action_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_chunk_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chat_sessions_doctor_patient', 'chat_sessions', ['doctor_id', 'patient_id'], unique=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('doctor_statuses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='doctor_statuses_doctor_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='doctor_statuses_pkey'),
    sa.UniqueConstraint('doctor_id', name='doctor_statuses_doctor_id_key')
    )
    op.create_index('ix_doctor_statuses_id', 'doctor_statuses', ['id'], unique=False)
    # ### end Alembic commands ###
