"""add_oauth_tokens_for_delinking

Revision ID: 70e05e24e9bb
Revises: cc6e35d530a0
Create Date: 2026-03-25 23:08:52.540831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70e05e24e9bb'
down_revision: Union[str, None] = 'cc6e35d530a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('ix_contact_messages_created_at', table_name='contact_messages')
    # op.drop_index('ix_contact_messages_email', table_name='contact_messages')
    # op.drop_index('ix_contact_messages_first_name', table_name='contact_messages')
    # op.drop_index('ix_contact_messages_read', table_name='contact_messages')
    # op.drop_table('contact_messages')
    # op.alter_column('chat_messages', 'id',
    #            existing_type=sa.UUID(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('chat_sessions', 'id',
    #            existing_type=sa.UUID(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.drop_index('ix_chat_sessions_doctor_patient', table_name='chat_sessions')
    # op.create_index('ix_chunk_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('users', sa.Column('google_access_token', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('apple_refresh_token', sa.Text(), nullable=True))
    # op.alter_column('organizations', 'timezone',
    #            existing_type=sa.VARCHAR(length=100),
    #            server_default=None,
    #            existing_nullable=True)
    # op.alter_column('organizations', 'date_format',
    #            existing_type=sa.VARCHAR(length=100),
    #            server_default=None,
    #            existing_nullable=True)
    # op.alter_column('users', 'auth_provider',
    #            existing_type=postgresql.ENUM('email', 'google', 'apple', name='auth_provider_enum'),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('users', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('users', 'account_status',
    #            existing_type=postgresql.ENUM('pending_onboarding', 'pending_verification', 'active', 'suspended', name='account_status'),
    #            server_default=None,
    #            existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'account_status',
               existing_type=postgresql.ENUM('pending_onboarding', 'pending_verification', 'active', 'suspended', name='account_status'),
               server_default=sa.text("'active'::account_status"),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'auth_provider',
               existing_type=postgresql.ENUM('email', 'google', 'apple', name='auth_provider_enum'),
               server_default=sa.text("'email'::auth_provider_enum"),
               existing_nullable=False)
    op.drop_column('users', 'apple_refresh_token')
    op.drop_column('users', 'google_access_token')
    op.alter_column('organizations', 'date_format',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'DD/MM/YYYY'::character varying"),
               existing_nullable=True)
    op.alter_column('organizations', 'timezone',
               existing_type=sa.VARCHAR(length=100),
               server_default=sa.text("'UTC'::character varying"),
               existing_nullable=True)
    op.drop_index('ix_chunk_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_chat_sessions_doctor_patient', 'chat_sessions', ['doctor_id', 'patient_id'], unique=False)
    op.alter_column('chat_sessions', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('chat_messages', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('contact_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='contact_messages_pkey')
    )
    op.create_index('ix_contact_messages_read', 'contact_messages', ['read'], unique=False)
    op.create_index('ix_contact_messages_first_name', 'contact_messages', ['first_name'], unique=False)
    op.create_index('ix_contact_messages_email', 'contact_messages', ['email'], unique=False)
    op.create_index('ix_contact_messages_created_at', 'contact_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###
