"""add ai_access_permission to data_access_grants

Revision ID: a211f97aebb3
Revises: f4ff70557c75
Create Date: 2026-03-02 18:56:46.253010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a211f97aebb3'
down_revision: Union[str, None] = 'f4ff70557c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # Use IF EXISTS to handle cases where tables/indexes were already dropped
    op.execute("DROP INDEX IF EXISTS ix_health_metrics_patient_id")
    op.execute("DROP TABLE IF EXISTS health_metrics")
    op.execute("DROP INDEX IF EXISTS ix_recent_doctors_doctor_id")
    op.execute("DROP INDEX IF EXISTS ix_recent_doctors_patient_id")
    op.execute("DROP TABLE IF EXISTS recent_doctors")
    op.execute("DROP INDEX IF EXISTS ix_recent_patients_doctor_id")
    op.execute("DROP INDEX IF EXISTS ix_recent_patients_patient_id")
    op.execute("DROP TABLE IF EXISTS recent_patients")
    
    # Add columns with defaults to avoid NOT NULL constraint errors on existing rows
    op.execute("ALTER TABLE data_access_grants ADD COLUMN IF NOT EXISTS ai_access_permission BOOLEAN NOT NULL DEFAULT FALSE")
    op.execute("ALTER TABLE data_access_grants ADD COLUMN IF NOT EXISTS access_level VARCHAR(50) NOT NULL DEFAULT 'read_only'")
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS processing_details JSONB")
    op.execute("ALTER TABLE documents ADD COLUMN IF NOT EXISTS total_chunks INTEGER NOT NULL DEFAULT 0")



def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'processing_details')
    op.drop_column('data_access_grants', 'access_level')
    op.drop_column('data_access_grants', 'ai_access_permission')
    op.create_table('recent_patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_patients_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_patients_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_patients_pkey')
    )
    op.create_index('ix_recent_patients_patient_id', 'recent_patients', ['patient_id'], unique=False)
    op.create_index('ix_recent_patients_doctor_id', 'recent_patients', ['doctor_id'], unique=False)
    op.create_table('recent_doctors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_doctors_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_doctors_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_doctors_pkey')
    )
    op.create_index('ix_recent_doctors_patient_id', 'recent_doctors', ['patient_id'], unique=False)
    op.create_index('ix_recent_doctors_doctor_id', 'recent_doctors', ['doctor_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='health_metrics_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='health_metrics_pkey')
    )
    op.create_index('ix_health_metrics_patient_id', 'health_metrics', ['patient_id'], unique=False)
    # ### end Alembic commands ###
