"""migrate_zoom_to_google_meet

Revision ID: f4ff70557c75
Revises: a43077f747d0
Create Date: 2026-02-25 18:55:38.741215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4ff70557c75'
down_revision: Union[str, None] = 'a43077f747d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_recent_doctors_doctor_id')
    op.execute('DROP INDEX IF EXISTS ix_recent_doctors_patient_id')
    op.execute('DROP TABLE IF EXISTS recent_doctors CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_recent_patients_doctor_id')
    op.execute('DROP INDEX IF EXISTS ix_recent_patients_patient_id')
    op.execute('DROP TABLE IF EXISTS recent_patients CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_health_metrics_patient_id')
    op.execute('DROP TABLE IF EXISTS health_metrics CASCADE')
    op.add_column('appointments', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.add_column('appointments', sa.Column('meet_link', sa.Text(), nullable=True))
    op.drop_column('appointments', 'meeting_id')
    op.drop_column('appointments', 'meeting_password')
    op.drop_column('appointments', 'join_url')
    op.drop_column('appointments', 'start_url')
    op.add_column('consultations', sa.Column('google_event_id', sa.String(length=255), nullable=True))
    op.add_column('consultations', sa.Column('meet_link', sa.Text(), nullable=True))
    op.alter_column('consultations', 'urgency_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('consultations', 'visit_state',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.drop_column('consultations', 'meeting_id')
    op.drop_column('consultations', 'join_url')
    op.drop_column('consultations', 'password')
    op.drop_column('consultations', 'start_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consultations', sa.Column('start_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('consultations', sa.Column('password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('consultations', sa.Column('join_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('consultations', sa.Column('meeting_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('consultations', 'visit_state',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'scheduled'::character varying"),
               existing_nullable=False)
    op.alter_column('consultations', 'urgency_level',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'normal'::character varying"),
               existing_nullable=False)
    op.drop_column('consultations', 'meet_link')
    op.drop_column('consultations', 'google_event_id')
    op.add_column('appointments', sa.Column('start_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('join_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('meeting_password', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('meeting_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('appointments', 'meet_link')
    op.drop_column('appointments', 'google_event_id')
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='health_metrics_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='health_metrics_pkey')
    )
    op.create_index('ix_health_metrics_patient_id', 'health_metrics', ['patient_id'], unique=False)
    op.create_table('recent_patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_patients_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_patients_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_patients_pkey')
    )
    op.create_index('ix_recent_patients_patient_id', 'recent_patients', ['patient_id'], unique=False)
    op.create_index('ix_recent_patients_doctor_id', 'recent_patients', ['doctor_id'], unique=False)
    op.create_table('recent_doctors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_doctors_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_doctors_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_doctors_pkey')
    )
    op.create_index('ix_recent_doctors_patient_id', 'recent_doctors', ['patient_id'], unique=False)
    op.create_index('ix_recent_doctors_doctor_id', 'recent_doctors', ['doctor_id'], unique=False)
    # ### end Alembic commands ###
