"""add_phase7_hipaa_models

Revision ID: 75dff2f64884
Revises: fe074cc8ef8e
Create Date: 2026-01-23 11:54:16.011655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75dff2f64884'
down_revision: Union[str, None] = 'fe074cc8ef8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_data_access_grants_doctor_id', table_name='data_access_grants')
    op.drop_index('ix_data_access_grants_patient_id', table_name='data_access_grants')
    op.drop_table('data_access_grants')
    op.drop_index('ix_ai_processing_queue_doctor_id', table_name='ai_processing_queue')
    op.drop_index('ix_ai_processing_queue_organization_id', table_name='ai_processing_queue')
    op.drop_index('ix_ai_processing_queue_patient_id', table_name='ai_processing_queue')
    op.drop_index('ix_ai_processing_queue_status', table_name='ai_processing_queue')
    op.drop_table('ai_processing_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_processing_queue',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('data_payload', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('request_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'processing', 'completed', 'failed', name='ai_queue_status'), autoincrement=False, nullable=False),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('processing_started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='ai_processing_queue_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='ai_processing_queue_organization_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='ai_processing_queue_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ai_processing_queue_pkey')
    )
    op.create_index('ix_ai_processing_queue_status', 'ai_processing_queue', ['status'], unique=False)
    op.create_index('ix_ai_processing_queue_patient_id', 'ai_processing_queue', ['patient_id'], unique=False)
    op.create_index('ix_ai_processing_queue_organization_id', 'ai_processing_queue', ['organization_id'], unique=False)
    op.create_index('ix_ai_processing_queue_doctor_id', 'ai_processing_queue', ['doctor_id'], unique=False)
    op.create_table('data_access_grants',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('appointment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('grant_reason', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('revoked_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], name='data_access_grants_appointment_id_fkey'),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='data_access_grants_doctor_id_fkey'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name='data_access_grants_patient_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='data_access_grants_pkey')
    )
    op.create_index('ix_data_access_grants_patient_id', 'data_access_grants', ['patient_id'], unique=False)
    op.create_index('ix_data_access_grants_doctor_id', 'data_access_grants', ['doctor_id'], unique=False)
    # ### end Alembic commands ###
