"""add_zoom_fields_to_appointment

Revision ID: fe074cc8ef8e
Revises: 1198592c6d2a
Create Date: 2026-01-23 11:30:12.121008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe074cc8ef8e'
down_revision: Union[str, None] = '1198592c6d2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meeting_id', sa.String(length=50), nullable=True))
    op.add_column('appointments', sa.Column('join_url', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('start_url', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('meeting_password', sa.String(length=50), nullable=True))
    op.alter_column('users', 'phone_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'license_number',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'license_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('users', 'phone_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('appointments', 'meeting_password')
    op.drop_column('appointments', 'start_url')
    op.drop_column('appointments', 'join_url')
    op.drop_column('appointments', 'meeting_id')
    # ### end Alembic commands ###
