"""create_tasks_table

Revision ID: a4b6883a1f45
Revises: f0dc6048fe0b
Create Date: 2026-01-23 07:47:42.136099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4b6883a1f45'
down_revision: Union[str, None] = 'f0dc6048fe0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
