"""Add status to data_access_grants

Revision ID: dec5e5a04348
Revises: 75dff2f64884
Create Date: 2026-02-01 19:50:06.979627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec5e5a04348'
down_revision: Union[str, None] = '75dff2f64884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_access_grants', sa.Column('status', sa.String(length=20), nullable=False, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_access_grants', 'status')
    # ### end Alembic commands ###
