"""ensure_social_auth_columns

Revision ID: 7e27fda403a5
Revises: f31176f5b920
Create Date: 2026-02-08 15:43:41.371373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e27fda403a5'
down_revision: Union[str, None] = 'f31176f5b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('apple_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('mfa_backup_codes', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_users_apple_id'), 'users', ['apple_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_apple_id'), table_name='users')
    op.drop_column('users', 'mfa_backup_codes')
    op.drop_column('users', 'apple_id')
    op.drop_column('users', 'google_id')
    # ### end Alembic commands ###
