"""add_dashboard_fields

Revision ID: a43077f747d0
Revises: a1b2c3d4e5f6
Create Date: 2026-02-23 00:01:44.897961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a43077f747d0'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS ix_health_metrics_patient_id')
    op.execute('DROP TABLE IF EXISTS health_metrics CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_recent_patients_doctor_id')
    op.execute('DROP INDEX IF EXISTS ix_recent_patients_patient_id')
    op.execute('DROP TABLE IF EXISTS recent_patients CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_recent_doctors_doctor_id')
    op.execute('DROP INDEX IF EXISTS ix_recent_doctors_patient_id')
    op.execute('DROP TABLE IF EXISTS recent_doctors CASCADE')
    op.alter_column('calendar_events', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('calendar_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.execute('DROP INDEX IF EXISTS idx_calendar_events_event_type')
    op.execute('DROP INDEX IF EXISTS idx_calendar_events_org_id')
    op.execute('DROP INDEX IF EXISTS idx_calendar_events_start_time')
    op.execute('DROP INDEX IF EXISTS idx_calendar_events_user_daterange')
    op.execute('DROP INDEX IF EXISTS idx_calendar_events_user_id')
    op.create_index(op.f('ix_calendar_events_event_type'), 'calendar_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_calendar_events_organization_id'), 'calendar_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_calendar_events_start_time'), 'calendar_events', ['start_time'], unique=False)
    op.create_index(op.f('ix_calendar_events_user_id'), 'calendar_events', ['user_id'], unique=False)
    op.add_column('consultations', sa.Column('urgency_level', sa.String(length=20), nullable=False, server_default='normal'))
    op.add_column('consultations', sa.Column('chief_complaint', sa.Text(), nullable=True))
    op.add_column('consultations', sa.Column('visit_state', sa.String(length=50), nullable=False, server_default='scheduled'))
    op.add_column('consultations', sa.Column('check_in_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('consultations', sa.Column('completion_time', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_consultations_urgency_level'), 'consultations', ['urgency_level'], unique=False)
    op.create_index(op.f('ix_consultations_visit_state'), 'consultations', ['visit_state'], unique=False)
    op.add_column('invitations', sa.Column('staff_status', sa.String(length=20), nullable=True))
    op.add_column('invitations', sa.Column('department_role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'department_role')
    op.drop_column('invitations', 'staff_status')
    op.drop_index(op.f('ix_consultations_visit_state'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_urgency_level'), table_name='consultations')
    op.drop_column('consultations', 'completion_time')
    op.drop_column('consultations', 'check_in_time')
    op.drop_column('consultations', 'visit_state')
    op.drop_column('consultations', 'chief_complaint')
    op.drop_column('consultations', 'urgency_level')
    op.drop_index(op.f('ix_calendar_events_user_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_start_time'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_organization_id'), table_name='calendar_events')
    op.drop_index(op.f('ix_calendar_events_event_type'), table_name='calendar_events')
    op.create_index('idx_calendar_events_user_id', 'calendar_events', ['user_id'], unique=False)
    op.create_index('idx_calendar_events_user_daterange', 'calendar_events', ['user_id', 'start_time', 'end_time'], unique=False)
    op.create_index('idx_calendar_events_start_time', 'calendar_events', ['start_time'], unique=False)
    op.create_index('idx_calendar_events_org_id', 'calendar_events', ['organization_id'], unique=False)
    op.create_index('idx_calendar_events_event_type', 'calendar_events', ['event_type'], unique=False)
    op.alter_column('calendar_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('calendar_events', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_table('recent_doctors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_doctors_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_doctors_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_doctors_pkey')
    )
    op.create_index('ix_recent_doctors_patient_id', 'recent_doctors', ['patient_id'], unique=False)
    op.create_index('ix_recent_doctors_doctor_id', 'recent_doctors', ['doctor_id'], unique=False)
    op.create_table('recent_patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_patients_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_patients_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_patients_pkey')
    )
    op.create_index('ix_recent_patients_patient_id', 'recent_patients', ['patient_id'], unique=False)
    op.create_index('ix_recent_patients_doctor_id', 'recent_patients', ['doctor_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='health_metrics_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='health_metrics_pkey')
    )
    op.create_index('ix_health_metrics_patient_id', 'health_metrics', ['patient_id'], unique=False)
    # ### end Alembic commands ###
