"""add_department_fields_to_org_and_user

Revision ID: 2c8b6c6a9d3d
Revises: add_chat_sessions
Create Date: 2026-03-06 16:54:58.401978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8b6c6a9d3d'
down_revision: Union[str, None] = 'add_chat_sessions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chunk_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.add_column('invitations', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('organizations', sa.Column('departments', sa.String(length=1000), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('department_role', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'department_role')
    op.drop_column('users', 'department')
    op.drop_column('organizations', 'departments')
    op.drop_column('invitations', 'department')
    op.drop_index('ix_chunk_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###
