"""make_patient_id_nullable_in_chat_history

Revision ID: 55aa6ec02023
Revises: f4ff70557c75
Create Date: 2026-03-01 14:16:12.171123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55aa6ec02023'
down_revision: Union[str, None] = 'f4ff70557c75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_recent_doctors_doctor_id")
    op.execute("DROP INDEX IF EXISTS ix_recent_doctors_patient_id")
    op.execute("DROP TABLE IF EXISTS recent_doctors CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_health_metrics_patient_id")
    op.execute("DROP TABLE IF EXISTS health_metrics CASCADE")
    op.execute("DROP INDEX IF EXISTS ix_recent_patients_doctor_id")
    op.execute("DROP INDEX IF EXISTS ix_recent_patients_patient_id")
    op.execute("DROP TABLE IF EXISTS recent_patients CASCADE")
    
    op.alter_column('chat_history', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True)
               
    # Add columns if they don't exist
    from sqlalchemy.engine.reflection import Inspector
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    
    # Check data_access_grants columns
    dag_cols = [c.get('name') for c in inspector.get_columns('data_access_grants')]
    if 'ai_access_permission' not in dag_cols:
        op.add_column('data_access_grants', sa.Column('ai_access_permission', sa.Boolean(), nullable=False, server_default='false'))
    if 'access_level' not in dag_cols:
        op.add_column('data_access_grants', sa.Column('access_level', sa.String(length=50), nullable=False, server_default='standard'))
        
    # Check documents columns
    doc_cols = [c.get('name') for c in inspector.get_columns('documents')]
    if 'processing_details' not in doc_cols:
        op.add_column('documents', sa.Column('processing_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    if 'total_chunks' not in doc_cols:
        op.add_column('documents', sa.Column('total_chunks', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'total_chunks')
    op.drop_column('documents', 'processing_details')
    op.drop_column('data_access_grants', 'access_level')
    op.drop_column('data_access_grants', 'ai_access_permission')
    op.alter_column('chat_history', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('recent_patients',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_patients_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_patients_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_patients_pkey')
    )
    op.create_index('ix_recent_patients_patient_id', 'recent_patients', ['patient_id'], unique=False)
    op.create_index('ix_recent_patients_doctor_id', 'recent_patients', ['doctor_id'], unique=False)
    op.create_table('health_metrics',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='health_metrics_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='health_metrics_pkey')
    )
    op.create_index('ix_health_metrics_patient_id', 'health_metrics', ['patient_id'], unique=False)
    op.create_table('recent_doctors',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('doctor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('last_visit_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('visit_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], name='recent_doctors_doctor_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='recent_doctors_patient_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='recent_doctors_pkey')
    )
    op.create_index('ix_recent_doctors_patient_id', 'recent_doctors', ['patient_id'], unique=False)
    op.create_index('ix_recent_doctors_doctor_id', 'recent_doctors', ['doctor_id'], unique=False)
    # ### end Alembic commands ###
